#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -P CSCI1142
#PBS -q normal
#PBS -l walltime=48:00:00
#PBS -m abe
#PBS -M scott.hallauer@gmail.com

ulimit -s unlimited

nproc=`cat $PBS_NODEFILE | wc -l`
echo nproc is $nproc
cat $PBS_NODEFILE

cd /mnt/lustre/users/shallauer/msc-project
module purge
module load chpc/python/anaconda/3-2021.11
module load chpc/BIOMODULES roborobo4
conda activate roborobo
python run.py -s config/ssga-short.properties test