#!/bin/bash
#PBS -l select=1:ncpus=24
#PBS -P CSCI1142
#PBS -q smp
#PBS -l walltime=96:00:00
#PBS -o /mnt/lustre/users/shallauer/jobs/mhom-m-10.out
#PBS -e /mnt/lustre/users/shallauer/jobs/mhom-m-10.err
#PBS -m abe
#PBS -M scott.hallauer@gmail.com

ulimit -s unlimited

module purge
module load chpc/BIOMODULES anaconda/3
module load chpc/BIOMODULES roborobo4

eval "$(conda shell.bash hook)"

conda activate roborobo

cd /mnt/lustre/users/shallauer/msc-project
nproc=`cat $PBS_NODEFILE | wc -l`
echo nproc is $nproc
cat $PBS_NODEFILE

SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -r output/run_mhom-m-01/checkpoints/gen_100.pkl
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -r output/run_mhom-m-02/checkpoints/gen_100.pkl
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -r output/run_mhom-m-03/checkpoints/gen_100.pkl
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -r output/run_mhom-m-04/checkpoints/gen_100.pkl
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -r output/run_mhom-m-05/checkpoints/gen_100.pkl
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -r output/run_mhom-m-06/checkpoints/gen_100.pkl
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -r output/run_mhom-m-07/checkpoints/gen_100.pkl
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -r output/run_mhom-m-08/checkpoints/gen_100.pkl
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -r output/run_mhom-m-09/checkpoints/gen_100.pkl
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python run.py -r output/run_mhom-m-10/checkpoints/gen_100.pkl

conda deactivate